### ISSUE TITLE
Send SMS with Androis-SMS-Gateway (webhook), doesn't work with MQTT version

### ISSUE THREAD

**Issue by raynoxfr** [ibnux/Android-SMS-Gateway-MQTT#1]
Hello,

I try to use your apps with MQTT version.
I have tried both (webhook and MQTT version) on the same mobile phone.

For webhook, it works for me.
For MQTT, I received the message from MQTT broker, and I have sent it with : 

```
{
    "to": "XXXXXXXX",
    "message": "test",
    "sim": 1
}
```

I received an answer :
`SUBMIT SMS SUCCESS:  XXXXXXXX SIM1`
But I don't receive any SMS to the destination.

Because it works with webhook app, so I don't think so it's an issue from my mobile phone.

For your information : 
- Galaxy S7 Edge (SM-G935F) with LineageOS 20-20240215-UNOFFICIAL-hero2lte

Thank you for your help

**Comment by raynoxfr** [comment]
```
2024-03-11 23:54:22.757 13518-13566 .smsgatewaymqtt         com.ibnux.smsgatewaymqtt             W  Accessing hidden method Landroid/os/ServiceManager;->getService(Ljava/lang/String;)Landroid/os/IBinder; (unsupported, reflection, allowed)
2024-03-11 23:54:22.807 13518-13566 .smsgatewaymqtt         com.ibnux.smsgatewaymqtt             W  Accessing hidden method Lcom/android/internal/telephony/ISms$Stub;->asInterface(Landroid/os/IBinder;)Lcom/android/internal/telephony/ISms; (unsupported, reflection, allowed)
2024-03-11 23:54:22.808 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  java.lang.NoSuchMethodException: com.android.internal.telephony.ISms$Stub$Proxy.sendText [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class android.app.PendingIntent, class android.app.PendingIntent]
2024-03-11 23:54:22.808 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at java.lang.Class.getMethod(Class.java:2937)
2024-03-11 23:54:22.809 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at java.lang.Class.getMethod(Class.java:2449)
2024-03-11 23:54:22.812 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at com.ibnux.smsgatewaymqtt.Utils.SimUtil.sendSMS(SimUtil.java:102)
2024-03-11 23:54:22.812 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at com.ibnux.smsgatewaymqtt.layanan.BackgroundService.sendSMSorUSSD(BackgroundService.java:441)
2024-03-11 23:54:22.812 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at com.ibnux.smsgatewaymqtt.layanan.BackgroundService.access$000(BackgroundService.java:62)
2024-03-11 23:54:22.812 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at com.ibnux.smsgatewaymqtt.layanan.BackgroundService$3$1.run(BackgroundService.java:278)
2024-03-11 23:54:22.812 13518-13566 System.err              com.ibnux.smsgatewaymqtt             W  	at java.lang.Thread.run(Thread.java:1012)
2024-03-11 23:54:22.876 13518-13537 EGL_emulation           com.ibnux.smsgatewaymqtt             D  app_time_stats: avg=35134.00ms min=35134.00ms max=35134.00ms count=1
```

**Comment by ibnux** [comment]
Try without bring sim variable.   
Only phone and text 

Multiple sim not available on all OS
